### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by hoijui** [glassbeadsoftware/snapmail-release#1]
hello! :-)
for people who do not know what this is. could you please add more description?
(including a link to the original SnapMail, probably)
I do not know what SnapMail is, and just came to this repo from the holochain forum summary email.
from the screenshot, it looks like a mail-client, so that is what it is in my mind as of now.

**Comment by ddd-mtl** [comment]
I've just updated the README with a lot more info. Should be better now.
