### ISSUE TITLE
replace logo image with transparent background or iconified (rounded) white frame

### ISSUE THREAD

**Issue by samcooley** [glassbeadsoftware/snapmail-release#2]
Example showing block white background on SnapMail logo image:
![Screenshot 2021-12-08 at 13 36 54](https://user-images.githubusercontent.com/1519349/145209787-4cc07626-ec8d-4fe2-92f4-1a10409b9650.png)

**Comment by samcooley** [comment]
Ummm, @ddd-mtl, looks like you already did this in or before 0.1.5-rc15?
![image](https://user-images.githubusercontent.com/1519349/145495637-868fa793-f82c-45e6-9bf3-aeb50bbda706.png)
Thanks!!!

**Comment by ddd-mtl** [comment]
Fixed in 0.1.5-rc15 yep
