### ISSUE TITLE
update packaging information

### ISSUE THREAD

**Issue by samcooley** [glassbeadsoftware/snapmail-release#3]
**electron/package.json**
  "description": "A minimalist P2P email application on holochain",
becomes:
  "description": "A minimalist P2P messaging application on Holochain",
and:
 "author": "Harris-Braun Enterprises, LLC and contributors",
becomes:
 "author": "Glass Bead Software, LLC and contributors",
and:
    "appId": "com.harris-braun.snapmail",
becomes:
    "appId": "com.glassbead.snapmail",
and:
    "copyright": "Copyright © 2021-2022 Harris-Braun Enterprises LLC",
becomes:
    "copyright": "Copyright © 2021-2022 Glass Bead Software LLC",

**electron/afterSignHook.js:**
  const appId = 'com.harris-braun.snapmail'
becomes:
  const appId = 'com.glassbead.snapmail'

**Comment by ddd-mtl** [comment]
Fixed in https://github.com/glassbeadsoftware/snapmail/commit/f3ef0ff3b7010ca2e23e1ff4627418ae6eb4aef5
